CREATE TABLE Loans (
	CopyID int FOREIGN KEY REFERENCES BookCopies(CopyID) NOT NULL,
	LenderID int FOREIGN KEY REFERENCES Accounts(UserID) NOT NULL,
	DueDate date NOT NULL,
	CONSTRAINT PK_Loan PRIMARY KEY (CopyID, LenderID)
)
GO